### ISSUE TITLE
Calculate Volatility (std deviation) for each asset

### ISSUE THREAD

**Issue by vaughnmck** [butterdao/whip#21]
Aggregate volatility for entire portfolio/treasury using weighted average. (Weights to be determined using market cap in USD)

**Comment by vaughnmck** [comment]
@acemasterjb @lajarre I assumed we were already calculating total portfolio volatility here: 

![Image](https://user-images.githubusercontent.com/7321643/171616884-c78c92d3-28e7-4650-82c6-d059c577ec2d.png)

Can you confirm how we're calculating this metric right now?

**Comment by acemasterjb** [comment]
@vaughnmck yes, right now we are attempting to calculate aggregate volatility using the historical balances of the treasuries.

I think that we can provide better data for this metric using weighted avgs, like you mentioned in your original post/comment; meme tokens airdropped to a treasury shouldn't be able skew the aggregate volatility of a respectable treasury.

**Comment by lajarre** [comment]
> I think that we can provide better data for this metric using weighted avgs, like you mentioned in your original post/comment; meme tokens airdropped to a treasury shouldn't be able skew the aggregate volatility of a respectable treasury.

What we're doing today is `volatility = mean of std deviation of returns of total balance over period`. It seems to me this is not going to take any spamcoin into account as they have no effect on the total balance itself, as they have no value.

Also, on a more formal level: if we display "volatility", we should apply the usual volatility calculation. From a quick internet search it seems that the basic volatility calculation is the one we are using, but sometimes the beta relative to an index is used. But we can definitely display something else than volatility if that ends up being more relevant for users.

**Comment by acemasterjb** [comment]
> It seems to me this is not going to take any spamcoin into account as they have no effect on the total balance itself, as they have no value.

Fundamentally, yes. However, Covalent does give a `quote_rate` for spam tokens such as `OMIC` so I don't think we should assume that for Whip; technically, Whip will show that these tokens have value if we don't filter/blacklist them.

If we can be more confident in our spam filter, then I am more comfortable with making that assumption. Otherwise, we should penalize them somehow.

Ultimately, there really isn't much you can do with spam tokens. I assume that it would be hard for a treasury to utilize the token for it's DAO members (difficult to sell/swap on exchanges, difficult to be used in yield farms, etc.)

I also agree that we should use standard functions for finding volatility to build trust with our users.
